---
version: "3.9"

services:
  overachieverr:
    build:
      context: .
      target: dev
    image: overachieverr:dev
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - "./:/app"
      - "~/.ssh:/home/abc/.ssh"
      - "~/.gnupg:/home/abc/.gnupg"
      - "~/.gitconfig:/home/abc/.gitconfig"
