---
version: "3.9"

services:
  overachieverr:
    build:
      context: .
      target: dev
    image: overachieverr:dev
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - "./:/app"
      - "~/.ssh:/home/dev/.ssh"
      - "~/.gnupg:/home/dev/.gnupg"
      - "~/.gitconfig:/home/dev/.gitconfig"
